const initState = {
  hadiths: {
    house1: {
      id: 'house1',
      title: 'hadith.house1.title',
      description: 'hadith.house1.description',
      hadith: 'hadith.house1.hadith',
      validationRate: 10,
      listRewards: [{ idRewards: 'house', numberRewardCorresponding: 1 }],
      emoji: '🏠',
      mainRewardId: 'house',
    },
    tree1: {
      id: 'tree1',
      title: 'hadith.tree1.title',
      description: 'hadith.tree1.description',
      hadith: 'hadith.tree1.hadith',
      validationRate: 4,
      listRewards: [{ idRewards: 'tree', numberRewardCorresponding: 4 }],
      emoji: '🌳',
      mainRewardId: 'tree',
    },
    tree2: {
      id: 'tree2',
      title: 'hadith.tree2.title',
      description: 'hadith.tree2.description',
      hadith: 'hadith.tree2.hadith',
      validationRate: 1,
      listRewards: [{ idRewards: 'palm', numberRewardCorresponding: 1 }],
      emoji: '🌴',
      mainRewardId: 'palm',
    },
    hassanats1: {
      id: 'hassanats1',
      title: 'hadith.hassanats1.title',
      description: 'hadith.hassanats1.description',
      hadith: 'hadith.hassanats1.hadith',
      validationRate: 100,
      listRewards: [
        { idRewards: 'hassanat', numberRewardCorresponding: 1000 },
        { idRewards: 'sayhat', numberRewardCorresponding: -1000 },
      ],
      emoji: '✅',
      mainRewardId: 'hassanat',
    },
    treasure1: {
      id: 'treasure1',
      title: 'hadith.treasure1.title',
      description: 'hadith.treasure1.description',
      hadith: 'hadith.treasure1.hadith',
      validationRate: 1,
      listRewards: [{ idRewards: 'treasure', numberRewardCorresponding: 1 }],
      emoji: '💰',
      mainRewardId: 'treasure',
    },
    quran1: {
      id: 'quran1',
      title: 'hadith.quran1.title',
      description: 'hadith.quran1.description',
      hadith: 'hadith.quran1.hadith',
      validationRate: 3,
      listRewards: [{ idRewards: 'quran', numberRewardCorresponding: 1 }],
      emoji: '📙',
      mainRewardId: 'quran',
    },
    quran2: {
      id: 'quran2',
      title: 'hadith.quran2.title',
      description: 'hadith.quran2.description',
      hadith: 'hadith.quran2.hadith',
      validationRate: 4,
      listRewards: [{ idRewards: 'quran', numberRewardCorresponding: 1 }],
      emoji: '📙',
      mainRewardId: 'quran',
    },
  },
  rewards: {
    house: {
      id: 'house',
      title: 'reward.house.title',
      listHadiths: ['house1'],
      emoji: '🏠',
    },
    tree: {
      id: 'tree',
      title: 'reward.tree.title',
      listHadiths: ['tree1'],
      emoji: '🌳',
    },
    palm: {
      id: 'palm',
      title: 'reward.palm.title',
      listHadiths: ['tree2'],
      emoji: '🌴',
    },
    hassanat: {
      id: 'hassanat',
      title: 'reward.hassanat.title',
      listHadiths: ['hassanats1'],
      emoji: '✅',
    },
    sayhat: {
      id: 'sayhat',
      title: 'reward.sayhat.title',
      listHadiths: ['hassanats1'],
      emoji: '❌',
    },
    treasure: {
      id: 'treasure',
      title: 'reward.treasure.title',
      listHadiths: ['treasure1'],
      emoji: '💰',
    },
    quran: {
      id: 'quran',
      title: 'reward.quran.title',
      listHadiths: ['quran1', 'quran2'],
      emoji: '📙',
    },
  },
  counters: {
    house1: 0,
    tree1: 0,
    tree2: 0,
    hassanats1: 0,
    treasure1: 0,
    quran1: 0,
    quran2: 0,
  },
};

export default initState;
